"""Persist and load Talishar URL env for training (multi-shard aware)."""

from __future__ import annotations

import os
from pathlib import Path

from fab_bridge.paths import repo_root

DEFAULT_TALISHAR_URL = "http://localhost:8080/game"

DEFAULT_SHARD_BASE_PORT = 8080
DEFAULT_TALISHAR_FE_URL = "http://localhost:5173"
_TRAINING_ENV_REL = Path("docker/talishar/talishar-training.local.env")
_MANAGED_KEYS = ("TALISHAR_URL", "TALISHAR_URLS", "TALISHAR_FE_URL")


def training_env_path() -> Path:
    return repo_root() / _TRAINING_ENV_REL


def load_env_file(path: Path) -> dict[str, str]:
    """Parse a dotenv-style file without writing into the process yet."""
    values: dict[str, str] = {}
    if not path.is_file():
        return values
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        key, sep, value = line.partition("=")
        if not sep:
            continue
        token = value.strip()
        if len(token) >= 2 and token[0] == token[-1] and token[0] in {"'", '"'}:
            token = token[1:-1]
        values[key.strip()] = token
    return values


def _format_env_line(key: str, value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'{key}="{escaped}"'


def shard_game_urls(*, shards: int, base_port: int = DEFAULT_SHARD_BASE_PORT) -> list[str]:
    count = max(1, int(shards))
    port = int(base_port)
    return [f"http://localhost:{port + index}/game" for index in range(count)]


def build_training_env_values(
    *,
    shards: int = 1,
    base_port: int = DEFAULT_SHARD_BASE_PORT,
    fe_url: str = DEFAULT_TALISHAR_FE_URL,
    urls: list[str] | None = None,
) -> dict[str, str]:
    if urls:
        from flesh_and_blood_rlbridge.talishar_backend_pool import (  # noqa: PLC0415
            normalize_talishar_url,
        )

        backend_urls = [normalize_talishar_url(u) for u in urls if str(u).strip()]
    else:
        backend_urls = list(shard_game_urls(shards=shards, base_port=base_port))
    if not backend_urls:
        backend_urls = [DEFAULT_TALISHAR_URL]
    values: dict[str, str] = {
        "TALISHAR_URL": backend_urls[0],
        "TALISHAR_FE_URL": fe_url.rstrip("/"),
    }
    if len(backend_urls) > 1:
        values["TALISHAR_URLS"] = ",".join(backend_urls)
    return values


def write_training_env(
    *,
    shards: int = 1,
    base_port: int = DEFAULT_SHARD_BASE_PORT,
    fe_url: str = DEFAULT_TALISHAR_FE_URL,
    urls: list[str] | None = None,
) -> dict[str, str]:
    """Write shard URLs for training scripts; returns the values written."""
    values = build_training_env_values(
        shards=shards,
        base_port=base_port,
        fe_url=fe_url,
        urls=urls,
    )
    path = training_env_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Auto-generated by start_talishar.py — do not edit while stacks are running.",
        _format_env_line("TALISHAR_URL", values["TALISHAR_URL"]),
        _format_env_line("TALISHAR_FE_URL", values["TALISHAR_FE_URL"]),
    ]
    if "TALISHAR_URLS" in values:
        lines.append(_format_env_line("TALISHAR_URLS", values["TALISHAR_URLS"]))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return values


def clear_training_env() -> None:
    path = training_env_path()
    if path.is_file():
        path.unlink()


def apply_training_env(*, override: bool = False) -> dict[str, str]:
    """Load ``talishar-training.local.env`` into ``os.environ`` if present."""
    values = load_env_file(training_env_path())
    for key in _MANAGED_KEYS:
        if key in values and (override or key not in os.environ):
            os.environ[key] = values[key]
        elif override and key not in values and key == "TALISHAR_URLS":
            os.environ.pop("TALISHAR_URLS", None)
    return values


def apply_training_env_values(values: dict[str, str]) -> None:
    """Apply freshly written values to the current process."""
    for key, value in values.items():
        os.environ[key] = value
    if "TALISHAR_URLS" not in values:
        os.environ.pop("TALISHAR_URLS", None)
