"""
rlbridge Flesh and Blood Environment (Talishar-Inspired)
====================================================
A turn-based TCG simulator inspired by Talishar-style gameplay loops.

This environment models the core Flesh and Blood gameplay loop:

- Two heroes (agent vs scripted opponent) with hand/deck/discard zones and
  draw-up-to-intellect each turn.
- Pitch economy: resources start at 0 each turn and are generated by pitching
  cards (by their pitch value); pitched cards go to the bottom of the deck.
- Action phase: pitch cards, then play attack actions (cost + 1 action point).
- Combat chain with reaction windows:
    * Defense phase: the defender may block with multiple cards.
    * Reaction phase: the attacker may play attack reactions to boost power.
- Keyword effects derived from card text: ``go again`` (chain another attack),
  ``dominate`` (defender limited to one blocking card), plus a requirement hook
  for "reveal a <type> card from hand" / fusion-style conditional bonuses.

Reward signal summary:

- Terminal win: `+1.0`; terminal loss: `-1.0`.
- Dense shaping: `+0.01 * damage_dealt` and `-0.005 * damage_received` per combat resolution.
- Step penalty of `-0.005` per step discourages passive play.
- Illegal actions receive a penalty (`-0.1`, except pass is auto-coerced when it is the only legal action).
- Invalid block/play attempts apply `-0.05`.
- Blocking carries no shaping bonus; win/loss is the primary signal.

The simulator is designed for training and protocol integration, not as a full
competitive-rules implementation.
"""

from __future__ import annotations

import base64
import functools
import importlib
import json
import math
import random
import re
from dataclasses import dataclass, field
from io import BytesIO
from pathlib import Path
from typing import Any, Optional

from rlbridge.protocol.messages import RenderResult, ResetResult, StepResult, TextSpace
from rlbridge.environments.base import rlbridgeEnvironment


_FAB_DB_DIR = Path(__file__).with_name("card_db")
_CARDS_PATH = _FAB_DB_DIR / "cards.json"
_HEROES_PATH = _FAB_DB_DIR / "heroes.json"
_FABRARY_DECKS_PATH = _FAB_DB_DIR / "fabrary_decks.json"
_CARD_VAULT_FEED_URL_CANDIDATES = (
    "https://cards.fabtcg.com/data/cards.json",
    "https://cards.fabtcg.com/cards.json",
    "https://cardvault.fabtcg.com/data/cards.json",
    "https://cardvault.fabtcg.com/cards.json",
    # Fallback mirror of official card-vault-compatible card records.
    "https://raw.githubusercontent.com/the-fab-cube/flesh-and-blood-cards/master/json/english/card.json",
)

_FORMAT_ALIASES = {
    "cc": "classic_constructed",
    "classic_constructed": "classic_constructed",
    "classic constructed": "classic_constructed",
    "silver_age": "silver_age",
    "silver age": "silver_age",
    "sage": "silver_age",
}


@dataclass(frozen=True)
class Card:
    id: str
    name: str
    pitch: int
    cost: int
    power: int
    defense: int
    type_line: str
    card_types: tuple[str, ...]
    card_class: str
    talent: Optional[str]
    rarity: str
    set_code: str
    keywords: tuple[str, ...]
    text: str
    legality: dict[str, str]


@dataclass(frozen=True)
class Hero:
    id: str
    name: str
    hero_class: str
    talent: Optional[str]
    life: int
    intellect: int
    weapon_name: str
    weapon_attack: int
    weapon_cost: int


@dataclass
class PlayerState:
    hero: Hero
    life: int
    resources: int
    action_points: int
    deck: list[str]
    hand: list[str]
    discard: list[str]
    pitch_zone: list[str] = field(default_factory=list)


@dataclass
class CombatState:
    attacker: int
    defender: int
    attack_card_id: str
    attack_power: int
    blocks: list[tuple[int, str, int]]
    attack_bonus: int = 0
    go_again: bool = False
    dominate: bool = False
    reaction_cards: list[str] = field(default_factory=list)


def _card_name_key(name: str) -> str:
    """Normalize card names for robust DB matching."""
    text = " ".join(str(name or "").strip().split())
    text = text.replace("||", "//")
    text = text.replace(" // ", "//")
    return text.lower()


# Keyword tokens we recognize in card rules text. Only ``go_again`` and
# ``dominate`` are mechanically simulated; the rest are surfaced for display
# and for requirement/bonus hooks.
_KEYWORD_PATTERNS: dict[str, str] = {
    "go_again": r"\bgo again\b",
    "dominate": r"\bdominate\b",
    "overpower": r"\boverpower\b",
    "intimidate": r"\bintimidate\b",
    "ward": r"\bward\b",
    "fusion": r"\bfusion\b",
    "battleworn": r"\bbattleworn\b",
    "blade_break": r"\bblade break\b",
    "arcane_barrier": r"\barcane barrier\b",
    "temper": r"\btemper\b",
}


def _derive_keywords(text: str) -> tuple[str, ...]:
    """Extract recognized FAB keywords from a card's rules text."""
    body = str(text or "").lower()
    if not body:
        return ()
    found = [kw for kw, pat in _KEYWORD_PATTERNS.items() if re.search(pat, body)]
    return tuple(found)


@functools.lru_cache(maxsize=4096)
def _reveal_requirement(text: str) -> tuple[Optional[str], bool]:
    """Parse a 'reveal a <X> card' clause from rules text.

    Returns ``(token, hard)`` where ``token`` is the required card descriptor
    (e.g. ``"lightning"``) and ``hard`` is True when the reveal is mandatory
    (no "you may" qualifier) rather than an optional bonus.
    """
    body = str(text or "").lower()
    match = re.search(r"reveal an?\s+([a-z]+)\s+card\s+from\s+(?:your\s+)?hand", body)
    if not match:
        return None, False
    token = match.group(1)
    pre = body[max(0, match.start() - 40):match.start()]
    # "you may reveal" / "Fusion - reveal" are optional bonuses, not gates.
    optional = "may" in pre or "fusion" in pre
    return token, not optional


def _load_cards() -> dict[str, Card]:
    if not _CARDS_PATH.exists():
        raise FileNotFoundError(f"Missing Flesh and Blood card DB at {_CARDS_PATH}")

    raw = json.loads(_CARDS_PATH.read_text(encoding="utf-8"))
    cards: dict[str, Card] = {}
    for rec in raw:
        text = rec.get("text", "")
        keywords = tuple(rec.get("keywords", [])) or _derive_keywords(text)
        card = Card(
            id=rec["id"],
            name=rec["name"],
            pitch=int(rec.get("pitch", 0)),
            cost=int(rec.get("cost", 0)),
            power=int(rec.get("power", 0)),
            defense=int(rec.get("defense", 0)),
            type_line=rec.get("type_line", ""),
            card_types=tuple(rec.get("card_types", [])),
            card_class=rec.get("class", "Generic"),
            talent=rec.get("talent"),
            rarity=rec.get("rarity", "Common"),
            set_code=rec.get("set", "SIM"),
            keywords=keywords,
            text=text,
            legality=rec.get("legality", {}),
        )
        cards[card.id] = card
    return cards


def _load_heroes() -> dict[str, Hero]:
    if not _HEROES_PATH.exists():
        raise FileNotFoundError(f"Missing Flesh and Blood hero DB at {_HEROES_PATH}")

    raw = json.loads(_HEROES_PATH.read_text(encoding="utf-8"))
    heroes: dict[str, Hero] = {}
    for rec in raw:
        weapon = rec.get("weapon", {})
        hero = Hero(
            id=rec["id"],
            name=rec["name"],
            hero_class=rec.get("class", "Generic"),
            talent=rec.get("talent"),
            life=int(rec.get("life", 40)),
            intellect=int(rec.get("intellect", 4)),
            weapon_name=weapon.get("name", "Basic Weapon"),
            weapon_attack=int(weapon.get("attack", 3)),
            weapon_cost=int(weapon.get("cost", 1)),
        )
        heroes[hero.id] = hero
    return heroes


class FleshAndBloodEnvironment(rlbridgeEnvironment):
    """Talishar-inspired RL simulator for Flesh and Blood gameplay loops."""

    def __init__(
        self,
        *,
        seed: Optional[int] = None,
        agent_hero_id: str = "hero_dorinthea_ironsong",
        opponent_hero_id: str = "hero_rhinar_reckless_rampage",
        max_turns: int = 60,
        deck_size: int = 36,
        agent_deck_style: str = "balanced",
        opponent_deck_style: str = "balanced",
        format: str = "classic_constructed",
        two_phase_deckbuild: bool = False,
        self_play: bool = False,
        opponent_type: str = "preset_logic",
        render_mode: Optional[str] = None,
    ) -> None:
        self._cards = _load_cards()
        self._heroes = _load_heroes()
        self._rng = random.Random(seed)

        if agent_hero_id not in self._heroes:
            raise ValueError(f"Unknown agent_hero_id: {agent_hero_id}")
        if opponent_hero_id not in self._heroes:
            raise ValueError(f"Unknown opponent_hero_id: {opponent_hero_id}")

        self._agent_hero_id = agent_hero_id
        self._opponent_hero_id = opponent_hero_id
        self._max_turns = max_turns
        self._deck_size = deck_size
        self._agent_deck_style = str(agent_deck_style)
        self._opponent_deck_style = str(opponent_deck_style)
        self._format = self._normalize_format(format)
        self._two_phase_deckbuild = bool(two_phase_deckbuild)

        self._players: list[PlayerState] = []
        self._turn = 0
        self._active_player = 0
        self._phase = "action"
        self._pending_combat: Optional[CombatState] = None
        self._initialized = False
        self._last_event = ""
        self._render_mode = render_mode
        self._self_play = self_play
        self._opponent_type = self._normalize_opponent_type(opponent_type)
        self._opponent_policy = self._build_opponent_policy(self._opponent_type)
        self._selection_stage = False
        self._selected_deck_option: Optional[dict[str, Any]] = None
        self._selected_opponent_deck_option: Optional[dict[str, Any]] = None
        self._card_vault_cards_cache: Optional[list[dict[str, Any]]] = None

    def reset(
        self,
        seed: Optional[int] = None,
        options: Optional[dict[str, Any]] = None,
    ) -> ResetResult:
        if seed is not None:
            self._rng.seed(seed)

        opts = options or {}
        self._agent_hero_id = str(opts.get("agent_hero_id", self._agent_hero_id))
        self._opponent_hero_id = str(opts.get("opponent_hero_id", self._opponent_hero_id))
        self._agent_deck_style = str(opts.get("agent_deck_style", self._agent_deck_style))
        self._opponent_deck_style = str(opts.get("opponent_deck_style", self._opponent_deck_style))
        self._format = self._normalize_format(str(opts.get("format", self._format)))
        self._two_phase_deckbuild = bool(opts.get("two_phase_deckbuild", self._two_phase_deckbuild))
        self._opponent_type = self._normalize_opponent_type(str(opts.get("opponent_type", self._opponent_type)))
        self._opponent_policy = self._build_opponent_policy(self._opponent_type)
        self._max_turns = int(opts.get("max_turns", self._max_turns))
        self._deck_size = int(opts.get("deck_size", self._deck_size))

        min_cards, max_cards = self._format_deck_bounds()
        self._deck_size = max(min_cards, min(self._deck_size, max_cards))

        self._pending_combat = None
        self._selected_deck_option = None
        self._selected_opponent_deck_option = None

        if self._two_phase_deckbuild:
            self._players = []
            self._turn = 0
            self._active_player = 0
            self._phase = "deck_selection"
            self._selection_stage = True
            self._last_event = "Select a deck to begin the match"
        else:
            self._selection_stage = False
            self._start_match(
                agent_hero_id=self._agent_hero_id,
                opponent_hero_id=self._opponent_hero_id,
                agent_deck_style=self._agent_deck_style,
                opponent_deck_style=self._opponent_deck_style,
            )

        self._initialized = True
        return ResetResult(
            observation=self._observation(),
            info={
                "legal_actions": self._legal_actions(),
                "agent_hero": (self._players[0].hero.name if self._players else None),
                "opponent_hero": (self._players[1].hero.name if self._players else None),
                "format": self._format,
                "opponent_type": self._opponent_type,
                "stage": ("deck_selection" if self._selection_stage else "play"),
            },
        )

    def step(self, action: Any) -> StepResult:
        if not self._initialized:
            raise RuntimeError("Call reset() before step().")

        if self._selection_stage:
            legal = self._legal_actions()
            parsed = self._normalize_action(action)
            if parsed not in legal:
                if isinstance(action, int) and legal:
                    parsed = legal[action % len(legal)]
                else:
                    return StepResult(
                        observation=self._observation(),
                        reward=-0.1,
                        terminated=False,
                        truncated=False,
                        info={
                            "error": f"Illegal action {parsed!r}",
                            "legal_actions": legal,
                        },
                    )

            choice_key = parsed.split(" ", 1)[1]
            choice = next((o for o in self._deck_options_for_format() if o["key"] == choice_key), None)
            if choice is None:
                return StepResult(
                    observation=self._observation(),
                    reward=-0.1,
                    terminated=False,
                    truncated=False,
                    info={"error": f"Unknown deck option: {choice_key}", "legal_actions": legal},
                )

            self._selected_deck_option = dict(choice)
            self._agent_hero_id = str(choice["hero_id"])
            self._deck_size = int(choice["deck_size"])

            opp_choice = self._sample_opponent_matchup(agent_hero_id=self._agent_hero_id)
            self._selected_opponent_deck_option = dict(opp_choice)
            self._opponent_hero_id = str(opp_choice["hero_id"])

            self._selection_stage = False
            # Pass pre-resolved card IDs when a fabrary deck option was chosen.
            agent_card_ids: Optional[list[str]] = choice.get("_card_ids")  # type: ignore[assignment]
            opp_card_ids: Optional[list[str]] = opp_choice.get("_card_ids")  # type: ignore[assignment]
            self._start_match(
                agent_hero_id=self._agent_hero_id,
                opponent_hero_id=self._opponent_hero_id,
                agent_deck_style=str(choice["style"]),
                opponent_deck_style=str(opp_choice["style"]),
                agent_deck_ids=agent_card_ids,
                opponent_deck_ids=opp_card_ids,
            )
            self._last_event = f"Deck selected: {choice['label']} | Matchup: {opp_choice['label']}"

            info = {
                "legal_actions": self._legal_actions(),
                "phase": self._phase,
                "last_event": self._last_event,
                "turn": self._turn,
                "stage": "play",
            }
            return StepResult(
                observation=self._observation(),
                reward=0.0,
                terminated=False,
                truncated=False,
                info=info,
            )

        legal = self._legal_actions()
        parsed = self._normalize_action(action)
        if parsed not in legal:
            if legal == ["pass"]:
                # Only pass is legal - coerce so policies never deadlock.
                parsed = "pass"
            elif isinstance(action, int) and legal:
                # RL agents emit integer indices; treat them as indices into the
                # legal action list so out-of-range ints never get stuck.
                parsed = legal[action % len(legal)]
            else:
                return StepResult(
                    observation=self._observation(),
                    reward=-0.1,
                    terminated=False,
                    truncated=False,
                    info={
                        "error": f"Illegal action {parsed!r}",
                        "legal_actions": legal,
                    },
                )

        reward = 0.0

        if self._self_play:
            reward += self._step_self_play(parsed)
        else:
            if self._phase == "action":
                if parsed == "pass":
                    self._last_event = "Agent passed turn"
                    self._pass_action(0)
                elif parsed.startswith("pitch "):
                    reward += self._do_pitch(0, int(parsed.split(" ")[1]))
                elif parsed.startswith("play "):
                    reward += self._do_play_attack(0, int(parsed.split(" ")[1]))
            elif self._phase == "defense":
                if parsed == "pass":
                    self._pass_defense(0)
                elif parsed.startswith("block "):
                    reward += self._do_block(0, int(parsed.split(" ")[1]))
            elif self._phase == "reaction":
                if parsed == "pass":
                    reward += self._resolve_and_advance(0)
                elif parsed.startswith("reaction "):
                    reward += self._do_reaction(0, int(parsed.split(" ")[1]))
            # Drive the scripted opponent until the agent must decide again.
            reward += self._auto_advance()

        terminated = self._is_terminal()
        truncated = self._turn >= self._max_turns and not terminated
        if truncated:
            self._last_event = "Reached max turns"

        # Terminal win/loss bonus (primary signal)
        if terminated:
            if self._self_play:
                # In self-play the acting player just caused termination;
                # reward from the perspective of the player whose life just hit 0.
                loser = next(i for i, p in enumerate(self._players) if p.life <= 0)
                winner = 1 - loser
                # Reward for the policy: +1 if the last acting player won, -1 if lost.
                if self._active_player == winner:
                    reward += 1.0
                else:
                    reward -= 1.0
            elif self._players[0].life <= 0:
                reward -= 1.0  # agent lost
            else:
                reward += 1.0  # agent won
        else:
            reward -= 0.005  # step penalty to discourage passive looping

        info = {
            "legal_actions": [] if (terminated or truncated) else self._legal_actions(),
            "phase": self._phase,
            "last_event": self._last_event,
            "turn": self._turn,
        }
        return StepResult(
            observation=self._observation(),
            reward=reward,
            terminated=terminated,
            truncated=truncated,
            info=info,
        )

    def close(self) -> None:
        self._players = []
        self._pending_combat = None
        self._initialized = False

    @property
    def observation_space(self) -> TextSpace:
        return TextSpace(min_length=0, max_length=16000)

    @property
    def action_space(self) -> TextSpace:
        return TextSpace(min_length=1, max_length=32)

    def sample_action(self) -> str:
        if not self._initialized:
            return "pass"
        if self._selection_stage:
            legal = self._legal_actions()
            return self._rng.choice(legal) if legal else "pass"
        if len(self._players) < 2:
            return "pass"
        legal = self._legal_actions()
        return self._rng.choice(legal) if legal else "pass"

    def render(self) -> RenderResult:
        if self._render_mode == "rgb_array":
            return self._render_rgb()
        return RenderResult(mode="ansi", text=self._render_text())

    def _render_rgb(self) -> RenderResult:
        try:
            from PIL import Image, ImageDraw, ImageFont
        except ImportError:
            return RenderResult(mode="rgb_array", text="pillow not installed")

        obs = self._observation()
        p_agent, p_opp = self._estimate_win_probabilities(obs)
        canvas_width, canvas_height = 1200, 720
        width, height = 1280, 720  # 720p output
        bg = (18, 24, 33)
        panel = (30, 40, 54)
        panel_alt = (41, 53, 69)
        accent = (245, 181, 82)
        fg = (240, 243, 248)
        sub = (176, 186, 201)
        enemy = (240, 103, 103)
        ally = (96, 214, 138)

        img = Image.new("RGB", (canvas_width, canvas_height), bg)
        draw = ImageDraw.Draw(img)

        try:
            font_title = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 28)
            font_subtitle = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 20)
            font_text = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 16)
            font_small = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 14)
        except Exception:
            font_title = ImageFont.load_default()
            font_subtitle = ImageFont.load_default()
            font_text = ImageFont.load_default()
            font_small = ImageFont.load_default()

        def _panel(x0: int, y0: int, x1: int, y1: int, fill: tuple[int, int, int]) -> None:
            draw.rounded_rectangle((x0, y0, x1, y1), radius=14, fill=fill)

        def _text(x: int, y: int, msg: str, font: Any, fill: tuple[int, int, int]) -> None:
            draw.text((x, y), msg, fill=fill, font=font)

        def _encode_image(image: Any) -> str:
            if image.size != (width, height):
                resampling = getattr(getattr(Image, "Resampling", Image), "LANCZOS")
                image = image.resize((width, height), resample=resampling)
            buf = BytesIO()
            image.save(buf, format="PNG")
            return base64.b64encode(buf.getvalue()).decode("ascii")

        if obs.get("stage") == "deck_selection":
            _text(24, 20, "Flesh and Blood (Talishar-inspired)", font_title, fg)
            _text(24, 58, f"Format: {obs['format']} | Stage: deck_selection", font_subtitle, sub)
            _panel(20, 100, 1180, 680, panel)
            _text(40, 128, "Choose a deck to start the episode", font_subtitle, accent)
            for i, item in enumerate(obs.get("deck_options", [])[:12]):
                _text(40, 170 + i * 34, f"[{i}] {item['label']} ({item['deck_size']} cards)", font_text, fg)
            legal = ", ".join(obs.get("legal_actions", [])[:12])
            _text(40, 640, f"Legal actions: {legal}", font_small, sub)
            b64 = _encode_image(img)
            return RenderResult(mode="rgb_array", data=b64, width=width, height=height)

        _text(24, 20, "Flesh and Blood (Talishar-inspired)", font_title, fg)
        _text(
            24,
            58,
            f"Turn {obs['turn']} | Format: {obs['format']} | Phase: {obs['phase']} | Active: P{obs['active_player']}",
            font_subtitle,
            sub,
        )

        _panel(20, 100, 580, 240, panel)
        _panel(620, 100, 1180, 240, panel)
        _panel(20, 260, 1180, 360, panel_alt)
        _panel(20, 380, 1180, 700, panel)

        agent = obs["agent"]
        opponent = obs["opponent"]

        _text(40, 120, "Agent", font_subtitle, ally)
        _text(40, 150, f"Hero: {agent['hero']}", font_text, fg)
        _text(40, 174, f"Life: {agent['life']}", font_text, fg)
        _text(220, 174, f"Resources: {agent['resources']}", font_text, fg)
        _text(440, 174, f"AP: {agent['action_points']}", font_text, fg)
        _text(40, 200, f"Deck: {agent['deck']}  Discard: {agent['discard']}", font_text, sub)
        _text(40, 224, f"Win %: {p_agent:.1%}", font_text, accent)

        _text(640, 120, "Opponent", font_subtitle, enemy)
        _text(640, 150, f"Hero: {opponent['hero']}", font_text, fg)
        _text(640, 174, f"Life: {opponent['life']}", font_text, fg)
        _text(820, 174, f"Resources: {opponent['resources']}", font_text, fg)
        _text(1040, 174, f"AP: {opponent['action_points']}", font_text, fg)
        _text(
            640,
            200,
            f"Deck: {opponent['deck']}  Discard: {opponent['discard']}  Hand: {opponent['hand_size']}",
            font_text,
            sub,
        )
        _text(640, 224, f"Win %: {p_opp:.1%}", font_text, accent)

        pending = obs.get("pending_combat")
        if pending:
            combat_line = (
                f"Combat | Attacker: P{pending['attacker']}  Defender: P{pending['defender']}  "
                f"{pending['attack_card']} ATK {pending['attack_power']}  BLOCK {pending['total_block']}"
            )
        else:
            combat_line = "Combat | none"
        _text(40, 292, combat_line, font_text, fg)
        _text(40, 320, f"Last event: {obs['last_event']}", font_text, sub)

        _text(40, 400, "Agent Hand", font_subtitle, accent)

        hand = agent["hand"]
        card_w, card_h = 215, 128
        cols = 5
        x_start = 40
        y_start = 432
        x_gap = 14
        y_gap = 12
        for idx, card in enumerate(hand[:15]):
            row = idx // cols
            col = idx % cols
            x0 = x_start + col * (card_w + x_gap)
            y0 = y_start + row * (card_h + y_gap)
            x1 = x0 + card_w
            y1 = y0 + card_h
            shade = panel_alt if idx % 2 == 0 else (36, 47, 62)
            draw.rounded_rectangle((x0, y0, x1, y1), radius=10, fill=shade)
            _text(x0 + 10, y0 + 8, f"[{card['index']}] {card['name'][:24]}", font_small, fg)
            _text(x0 + 10, y0 + 34, f"Cost {card['cost']}  ATK {card['power']}  DEF {card['defense']}", font_small, sub)
            ctype = ",".join(card.get("card_types", []))[:28]
            _text(x0 + 10, y0 + 58, f"Type: {ctype}", font_small, sub)
            keys = ",".join(card.get("keywords", [])) or "none"
            _text(x0 + 10, y0 + 82, f"Keywords: {keys[:24]}", font_small, sub)

        legal = ", ".join(obs.get("legal_actions", [])[:12])
        _text(40, 676, f"Legal actions: {legal}", font_small, sub)

        b64 = _encode_image(img)
        return RenderResult(mode="rgb_array", data=b64, width=width, height=height)

    def _new_player(self, hero: Hero, hero_slot: int, deck_style: str = "balanced", deck_ids: Optional[list[str]] = None) -> PlayerState:
        if deck_ids is not None:
            deck = list(deck_ids)
        else:
            deck = self._build_deck(hero, deck_style=deck_style)
        self._rng.shuffle(deck)
        return PlayerState(
            hero=hero,
            life=self._starting_life(hero),
            resources=0,
            action_points=0,
            deck=deck,
            hand=[],
            discard=[],
        )

    def _build_deck(self, hero: Hero, deck_style: str = "balanced") -> list[str]:
        candidates: list[Card] = []
        for card in self._cards.values():
            if not self._is_card_legal_for_format(card.id):
                continue
            if not self._is_card_compatible_with_hero(card, hero):
                continue
            if not self._is_deck_candidate(card):
                continue
            candidates.append(card)

        if not candidates:
            raise ValueError(f"No legal cards available for hero={hero.name!r} format={self._format}")

        if deck_style == "aggro":
            ranked = sorted(
                candidates,
                key=lambda c: (
                    1 if "attack_action" in c.card_types else 0,
                    c.power,
                    -c.cost,
                    c.defense,
                ),
                reverse=True,
            )
        elif deck_style == "control":
            ranked = sorted(
                candidates,
                key=lambda c: (
                    c.defense,
                    c.pitch,
                    1 if "defense_reaction" in c.card_types else 0,
                    1 if "attack_action" in c.card_types else 0,
                ),
                reverse=True,
            )
        else:
            ranked = sorted(
                candidates,
                key=lambda c: (
                    (c.power + c.defense),
                    c.pitch,
                    1 if "attack_action" in c.card_types else 0,
                ),
                reverse=True,
            )

        copy_limit = 2 if self._format == "silver_age" else 3
        deck: list[str] = []
        counts: dict[str, int] = {}

        while len(deck) < self._deck_size:
            added_this_pass = False
            for card in ranked:
                cid = card.id
                if counts.get(cid, 0) >= copy_limit:
                    continue
                deck.append(cid)
                counts[cid] = counts.get(cid, 0) + 1
                added_this_pass = True
                if len(deck) >= self._deck_size:
                    break
            if not added_this_pass:
                deck.append(self._rng.choice(ranked).id)

        return deck[: self._deck_size]

    def _normalize_format(self, fmt: str) -> str:
        normalized = _FORMAT_ALIASES.get(str(fmt).strip().lower())
        if normalized is None:
            allowed = ", ".join(sorted(set(_FORMAT_ALIASES.values())))
            raise ValueError(f"Unknown format {fmt!r}. Expected one of: {allowed}")
        return normalized

    def _normalize_opponent_type(self, opponent_type: str) -> str:
        key = str(opponent_type or "").strip().lower().replace("-", "_")
        aliases = {
            "preset": "preset_logic",
            "preset_logic": "preset_logic",
            "random": "random",
            "self_play": "self_play",
            "selfplay": "self_play",
        }
        normalized = aliases.get(key)
        return normalized if normalized is not None else "preset_logic"

    def _build_opponent_policy(self, opponent_type: str) -> Any:
        from .opponents.preset_logic import PresetLogicOpponent

        if opponent_type == "preset_logic":
            return PresetLogicOpponent()
        if opponent_type == "random":
            from .opponents.random import RandomOpponent

            return RandomOpponent()
        if opponent_type == "self_play":
            from .opponents.self_play import SelfPlayOpponent

            return SelfPlayOpponent()
        return PresetLogicOpponent()

    def _format_deck_bounds(self) -> tuple[int, int]:
        if self._format == "silver_age":
            return 40, 55
        return 60, 80

    def _deck_options_for_format(self) -> list[dict[str, Any]]:
        min_cards, max_cards = self._format_deck_bounds()
        secondary_size = min(max_cards, min_cards + 5)
        options: list[dict[str, Any]] = []
        for hero in self._hero_pool_for_format():
            slug = hero.id.replace("hero_", "")
            options.append(
                {
                    "key": f"{slug}_aggro",
                    "label": f"{hero.name} Aggro",
                    "hero_id": hero.id,
                    "style": "aggro",
                    "deck_size": min_cards,
                }
            )
            options.append(
                {
                    "key": f"{slug}_control",
                    "label": f"{hero.name} Control",
                    "hero_id": hero.id,
                    "style": "control",
                    "deck_size": secondary_size,
                }
            )
        # Append fabrary deck options (distinct keys prefixed with "fab_")
        options.extend(self._fabrary_deck_options_for_format())
        return options

    def _sample_opponent_matchup(self, agent_hero_id: str) -> dict[str, Any]:
        options = self._deck_options_for_format()
        candidates = [o for o in options if str(o["hero_id"]) != agent_hero_id]
        if not candidates:
            candidates = options
        return dict(self._rng.choice(candidates))

    # ------------------------------------------------------------------
    # Fabrary deck database
    # ------------------------------------------------------------------

    def _load_fabrary_db(self) -> list[dict[str, Any]]:
        """Load and return raw deck entries from fabrary_decks.json."""
        if not _FABRARY_DECKS_PATH.exists():
            return []
        try:
            data = json.loads(_FABRARY_DECKS_PATH.read_text(encoding="utf-8"))
            return list(data.get("decks", []))
        except Exception:
            return []

    def _load_card_vault_feed(self) -> list[dict[str, Any]]:
        """Load raw card records from the official card vault (or fallback mirror)."""
        if self._card_vault_cards_cache is not None:
            return self._card_vault_cards_cache

        try:
            importer = importlib.import_module("flesh_and_blood_rlbridge.card_db.import_from_talishar")
        except Exception:
            self._card_vault_cards_cache = []
            return self._card_vault_cards_cache

        load_cards = getattr(importer, "load_cards", None)
        if load_cards is None:
            self._card_vault_cards_cache = []
            return self._card_vault_cards_cache

        for source_url in _CARD_VAULT_FEED_URL_CANDIDATES:
            try:
                records = load_cards(path=None, source_url=source_url)
                if isinstance(records, list) and records:
                    self._card_vault_cards_cache = records
                    return records
            except Exception:
                continue

        self._card_vault_cards_cache = []
        return self._card_vault_cards_cache

    def _import_missing_cards_from_card_vault(self, card_names: list[str]) -> int:
        """Append missing cards to cards.json by scanning card-vault data."""
        targets = {_card_name_key(name) for name in card_names if str(name).strip()}
        if not targets:
            return 0

        raw_records = self._load_card_vault_feed()
        if not raw_records:
            return 0

        by_name: dict[str, list[dict[str, Any]]] = {}
        for rec in raw_records:
            if not isinstance(rec, dict):
                continue
            key = _card_name_key(rec.get("name", ""))
            if not key:
                continue
            by_name.setdefault(key, []).append(rec)

        selected: list[dict[str, Any]] = []
        for key in sorted(targets):
            selected.extend(by_name.get(key, []))
        if not selected:
            return 0

        try:
            importer = importlib.import_module("flesh_and_blood_rlbridge.card_db.import_from_talishar")
            normalize_record = getattr(importer, "normalize_record", None)
            if normalize_record is None:
                return 0
        except Exception:
            return 0

        try:
            current_cards = json.loads(_CARDS_PATH.read_text(encoding="utf-8"))
            if not isinstance(current_cards, list):
                return 0
        except Exception:
            return 0

        existing_ids = {str(rec.get("id", "")) for rec in current_cards if isinstance(rec, dict)}
        normalized_new: list[dict[str, Any]] = []
        for rec in selected:
            try:
                norm = normalize_record(rec)
            except Exception:
                continue
            card_id = str(norm.get("id", ""))
            if not card_id or card_id in existing_ids:
                continue
            existing_ids.add(card_id)
            normalized_new.append(norm)

        if not normalized_new:
            return 0

        current_cards.extend(normalized_new)
        _CARDS_PATH.write_text(json.dumps(current_cards, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")
        self._cards = _load_cards()
        return len(normalized_new)

    def _build_name_lookup(self, hero: Hero) -> dict[str, list[Card]]:
        """Build normalized card-name lookup restricted to hero and format legality."""
        by_name: dict[str, list[Card]] = {}
        for card in self._cards.values():
            if not self._is_card_legal_for_format(card.id):
                continue
            if not self._is_deck_candidate(card):
                continue
            if not self._is_card_compatible_with_hero(card, hero):
                continue
            by_name.setdefault(_card_name_key(card.name), []).append(card)
        return by_name

    def _resolve_fabrary_deck(self, deck_entry: dict[str, Any]) -> list[str]:
        """Map a fabrary deck entry to a list of card IDs legal for the current format.

        Strategy:
        - For each {name, count} entry look up all pitch versions of that card
          that are legal and compatible with the hero.
        - Include up to ``count`` copies of *each* pitch version found.
        - Apply the per-card-ID copy limit (2 for silver_age, 3 for CC).
        - If the list exceeds ``max_deck_size`` it is randomly trimmed.
        - If it falls below ``min_deck_size`` it is padded with generic filler.
        """
        hero_id = str(deck_entry.get("hero_id", ""))
        if hero_id not in self._heroes:
            return []
        hero = self._heroes[hero_id]

        # Build name → [Card, ...] lookup restricted to this hero + format.
        by_name = self._build_name_lookup(hero)

        missing_names: list[str] = []
        for entry in deck_entry.get("cards", []):
            raw_name = str(entry.get("name", "")).strip()
            if raw_name and _card_name_key(raw_name) not in by_name:
                missing_names.append(raw_name)
        if missing_names:
            imported = self._import_missing_cards_from_card_vault(missing_names)
            if imported > 0:
                by_name = self._build_name_lookup(hero)

        copy_limit = 2 if self._format == "silver_age" else 3
        deck: list[str] = []

        for entry in deck_entry.get("cards", []):
            raw_name = str(entry.get("name", "")).strip()
            count = max(1, int(entry.get("count", 1)))
            matches = by_name.get(_card_name_key(raw_name), [])
            if not matches:
                continue  # card not in DB or not legal/compatible for this hero+format
            per_copy = min(count, copy_limit)
            # Sort pitch=1 (red) first so trimming preserves the strongest copies.
            for card in sorted(matches, key=lambda c: c.pitch):
                deck.extend([card.id] * per_copy)

        if not deck:
            return []

        min_cards, max_cards = self._format_deck_bounds()

        # Trim excess randomly if deck exceeds format maximum.
        if len(deck) > max_cards:
            self._rng.shuffle(deck)
            deck = deck[:max_cards]

        # Pad below minimum with generic legal filler cards.
        if len(deck) < min_cards:
            existing_ids = set(deck)
            filler_pool = [
                c for c in self._cards.values()
                if self._is_card_legal_for_format(c.id)
                and self._is_deck_candidate(c)
                and self._is_card_compatible_with_hero(c, hero)
                and c.id not in existing_ids
            ]
            self._rng.shuffle(filler_pool)
            for filler in filler_pool:
                if len(deck) >= min_cards:
                    break
                deck.append(filler.id)

        return deck

    def _fabrary_deck_options_for_format(self) -> list[dict[str, Any]]:
        """Return deck option dicts for all fabrary decks matching the current format.

        Each option has the same shape as procedural options plus extra fields:
        ``source``, ``source_url``, ``description``, and ``_card_ids``
        (the pre-resolved card ID list used by ``_new_player``).
        Keys are prefixed with ``"fab_"`` to avoid collisions with procedural keys.
        """
        raw_decks = self._load_fabrary_db()
        options: list[dict[str, Any]] = []
        for deck_entry in raw_decks:
            if str(deck_entry.get("format", "")) != self._format:
                continue
            hero_id = str(deck_entry.get("hero_id", ""))
            if hero_id not in self._heroes:
                continue
            card_ids = self._resolve_fabrary_deck(deck_entry)
            if not card_ids:
                continue
            options.append(
                {
                    "key": deck_entry["id"],
                    "label": deck_entry.get("name", deck_entry["id"]),
                    "hero_id": hero_id,
                    "style": str(deck_entry.get("style", "balanced")),
                    "deck_size": len(card_ids),
                    "source": "fabrary",
                    "source_url": deck_entry.get("source_url", ""),
                    "description": deck_entry.get("description", ""),
                    "_card_ids": card_ids,
                }
            )
        return options

    def _start_match(
        self,
        *,
        agent_hero_id: str,
        opponent_hero_id: str,
        agent_deck_style: str,
        opponent_deck_style: str,
        agent_deck_ids: Optional[list[str]] = None,
        opponent_deck_ids: Optional[list[str]] = None,
    ) -> None:
        self._players = [
            self._new_player(self._heroes[agent_hero_id], hero_slot=0, deck_style=agent_deck_style, deck_ids=agent_deck_ids),
            self._new_player(self._heroes[opponent_hero_id], hero_slot=1, deck_style=opponent_deck_style, deck_ids=opponent_deck_ids),
        ]
        self._turn = 1
        self._active_player = 0
        self._phase = "action"
        self._pending_combat = None
        self._last_event = "Game start"
        self._draw_up(0)
        self._draw_up(1)
        self._start_turn(0)

    def _starting_life(self, hero: Hero) -> int:
        # Talishar profile: Silver Age uses young-hero life profile.
        if self._format == "silver_age":
            return min(hero.life, 20)
        return hero.life

    def _is_deck_candidate(self, card: Card) -> bool:
        if "hero" in card.card_types:
            return False
        if "attack_action" in card.card_types:
            return True
        if card.defense > 0:
            return True
        return False

    def _is_card_compatible_with_hero(self, card: Card, hero: Hero) -> bool:
        card_class = (card.card_class or "Generic").strip().upper()
        hero_class = (hero.hero_class or "Generic").strip().upper()
        if card_class not in {"", "GENERIC", "NONE"} and card_class != hero_class:
            return False

        card_talent = (card.talent or "").strip().upper()
        hero_talent = (hero.talent or "").strip().upper()
        if card_talent not in {"", "NONE"} and card_talent != hero_talent:
            return False

        return True

    def _hero_pool_for_format(self) -> list[Hero]:
        heroes = list(self._heroes.values())
        if self._format == "silver_age":
            filtered = [h for h in heroes if h.life < 30]
        else:
            filtered = [h for h in heroes if h.life >= 30]
        if not filtered:
            filtered = heroes
        filtered.sort(key=lambda h: h.name.lower())
        return filtered

    def _is_card_legal_for_format(self, card_id: str) -> bool:
        card = self._cards[card_id]
        if self._format == "classic_constructed":
            return str(card.legality.get("classic_constructed", "legal")).lower() == "legal"

        if self._format == "silver_age":
            return str(card.legality.get("silver_age", "banned")).lower() == "legal"

        return True

    def _draw_card(self, player_idx: int) -> bool:
        p = self._players[player_idx]
        if not p.deck and p.discard:
            p.deck = p.discard
            p.discard = []
            self._rng.shuffle(p.deck)
        if not p.deck:
            return False
        p.hand.append(p.deck.pop())
        return True

    def _draw_up(self, player_idx: int) -> None:
        p = self._players[player_idx]
        while len(p.hand) < p.hero.intellect:
            if not self._draw_card(player_idx):
                break

    def _start_turn(self, player_idx: int) -> None:
        p = self._players[player_idx]
        p.resources = 0
        p.action_points = 1
        self._active_player = player_idx
        self._phase = "action"

    def _end_turn(self, player_idx: int) -> None:
        p = self._players[player_idx]
        # Pitched cards go to the bottom of the deck; the hand is kept.
        if p.pitch_zone:
            p.deck[:0] = p.pitch_zone
            p.pitch_zone = []
        self._draw_up(player_idx)
        p.resources = 0
        p.action_points = 0
        self._turn += 1

    # ------------------------------------------------------------------
    # Requirement / bonus hooks
    # ------------------------------------------------------------------
    def _reveal_available(self, player_idx: int, exclude_idx: int, token: str) -> bool:
        """True if the player can reveal another hand card matching ``token``."""
        token = (token or "").strip().lower()
        if not token:
            return False
        for i, cid in enumerate(self._players[player_idx].hand):
            if i == exclude_idx:
                continue
            c = self._cards[cid]
            haystack = " ".join(
                [c.name.lower(), (c.talent or "").lower(), c.text.lower(), " ".join(c.keywords)]
            )
            if token in haystack:
                return True
        return False

    def _play_blocked_reason(self, player_idx: int, hand_idx: int, card: Card) -> Optional[str]:
        """Return a reason string if a mandatory play requirement is unmet."""
        token, hard = _reveal_requirement(card.text)
        if token and hard and not self._reveal_available(player_idx, hand_idx, token):
            return f"{card.name} requires revealing a {token} card from hand"
        return None

    def _fusion_bonus_available(self, player_idx: int, hand_idx: int, card: Card) -> bool:
        """Fusion grants its bonus when a same-talent card can be revealed."""
        return self._reveal_available(player_idx, hand_idx, (card.talent or "").lower())

    # ------------------------------------------------------------------
    # Legal-move helpers (shared by the engine and observation)
    # ------------------------------------------------------------------
    def _legal_plays(self, actor_idx: int) -> list[int]:
        actor = self._players[actor_idx]
        if actor.action_points <= 0:
            return []
        plays: list[int] = []
        for i, cid in enumerate(actor.hand):
            card = self._cards[cid]
            if "attack_action" not in card.card_types:
                continue
            if card.cost > actor.resources:
                continue
            if self._play_blocked_reason(actor_idx, i, card):
                continue
            plays.append(i)
        return plays

    def _legal_pitches(self, actor_idx: int) -> list[int]:
        actor = self._players[actor_idx]
        return [i for i, cid in enumerate(actor.hand) if self._cards[cid].pitch > 0]

    def _legal_blocks(self, defender_idx: int) -> list[int]:
        combat = self._pending_combat
        if combat is None:
            return []
        # Dominate: the defender may use at most one blocking card.
        if combat.dominate and any(b[0] == defender_idx for b in combat.blocks):
            return []
        return [i for i, cid in enumerate(self._players[defender_idx].hand) if self._cards[cid].defense > 0]

    def _legal_reactions(self, attacker_idx: int) -> list[int]:
        attacker = self._players[attacker_idx]
        reactions: list[int] = []
        for i, cid in enumerate(attacker.hand):
            card = self._cards[cid]
            if "attack_reaction" in card.card_types and card.cost <= attacker.resources:
                reactions.append(i)
        return reactions

    # ------------------------------------------------------------------
    # Low-level state mutators (used by both human/agent and opponent)
    # ------------------------------------------------------------------
    def _do_pitch(self, player_idx: int, hand_idx: int) -> float:
        p = self._players[player_idx]
        card = self._cards[p.hand[hand_idx]]
        if card.pitch <= 0:
            self._last_event = f"{card.name} cannot be pitched"
            return -0.05
        p.hand.pop(hand_idx)
        p.pitch_zone.append(card.id)
        p.resources += card.pitch
        self._last_event = f"P{player_idx} pitches {card.name} (+{card.pitch} resources)"
        return 0.0

    def _do_play_attack(self, player_idx: int, hand_idx: int) -> float:
        attacker = self._players[player_idx]
        card = self._cards[attacker.hand[hand_idx]]

        if "attack_action" not in card.card_types:
            self._last_event = f"{card.name} is not an attack action"
            return -0.05
        if attacker.action_points <= 0:
            self._last_event = "No action points remaining"
            return -0.05
        if attacker.resources < card.cost:
            self._last_event = f"Need {card.cost} resources (pitch cards first)"
            return -0.05
        reason = self._play_blocked_reason(player_idx, hand_idx, card)
        if reason:
            self._last_event = reason
            return -0.05

        keywords = set(card.keywords)
        go_again = "go_again" in keywords
        fused = "fusion" in keywords and self._fusion_bonus_available(player_idx, hand_idx, card)
        if fused:
            go_again = True

        attacker.resources -= card.cost
        attacker.action_points -= 1
        attacker.hand.pop(hand_idx)

        self._pending_combat = CombatState(
            attacker=player_idx,
            defender=1 - player_idx,
            attack_card_id=card.id,
            attack_power=card.power,
            blocks=[],
            go_again=go_again,
            dominate=("dominate" in keywords),
        )
        suffix = " [fused]" if fused else (" [go again]" if go_again else "")
        self._last_event = f"P{player_idx} attacks with {card.name} ({card.power}){suffix}"
        self._enter_defense()
        return 0.0

    def _do_block(self, defender_idx: int, hand_idx: int) -> float:
        combat = self._pending_combat
        if combat is None:
            self._last_event = "No attack to defend"
            return -0.05
        blocker = self._players[defender_idx]
        card = self._cards[blocker.hand[hand_idx]]
        if card.defense <= 0:
            self._last_event = f"{card.name} cannot block"
            return -0.05
        blocker.hand.pop(hand_idx)
        blocker.discard.append(card.id)
        combat.blocks.append((defender_idx, card.id, card.defense))
        self._last_event = f"P{defender_idx} blocks with {card.name} (+{card.defense} defense)"
        return 0.0

    def _do_reaction(self, attacker_idx: int, hand_idx: int) -> float:
        combat = self._pending_combat
        if combat is None:
            self._last_event = "No attack in progress"
            return -0.05
        attacker = self._players[attacker_idx]
        card = self._cards[attacker.hand[hand_idx]]
        if "attack_reaction" not in card.card_types:
            self._last_event = f"{card.name} is not an attack reaction"
            return -0.05
        if card.cost > attacker.resources:
            self._last_event = f"Need {card.cost} resources for {card.name}"
            return -0.05
        attacker.resources -= card.cost
        attacker.hand.pop(hand_idx)
        combat.attack_bonus += card.power
        combat.reaction_cards.append(card.id)
        if "go_again" in card.keywords:
            combat.go_again = True
        self._last_event = f"P{attacker_idx} boosts with {card.name} (+{card.power} power)"
        return 0.0

    # ------------------------------------------------------------------
    # Phase transitions
    # ------------------------------------------------------------------
    def _enter_defense(self) -> None:
        combat = self._pending_combat
        self._phase = "defense"
        self._active_player = combat.defender

    def _enter_reaction(self) -> None:
        combat = self._pending_combat
        self._phase = "reaction"
        self._active_player = combat.attacker

    def _pass_action(self, player_idx: int) -> None:
        self._end_turn(player_idx)
        self._start_turn(1 - player_idx)

    def _pass_defense(self, defender_idx: int) -> None:
        if self._pending_combat is None:
            self._phase = "action"
            return
        self._enter_reaction()

    def _resolve_and_advance(self, perspective_idx: int) -> float:
        combat = self._pending_combat
        if combat is None:
            return 0.0
        attacker_idx = combat.attacker
        defender_idx = combat.defender
        attacker = self._players[attacker_idx]
        defender = self._players[defender_idx]

        total_block = sum(b[2] for b in combat.blocks)
        total_power = combat.attack_power + combat.attack_bonus
        damage = max(0, total_power - total_block)
        defender.life -= damage

        attacker.discard.append(combat.attack_card_id)
        attacker.discard.extend(combat.reaction_cards)
        go_again = combat.go_again
        self._pending_combat = None
        self._last_event = (
            f"P{attacker_idx} hits P{defender_idx} for {damage} "
            f"(power {total_power} vs block {total_block})"
        )

        if go_again:
            attacker.action_points += 1

        if not self._is_terminal():
            if attacker.action_points > 0:
                self._phase = "action"
                self._active_player = attacker_idx
            else:
                self._end_turn(attacker_idx)
                self._start_turn(defender_idx)

        if damage <= 0:
            return 0.0
        reward = float(damage) * 0.01
        return reward if perspective_idx == attacker_idx else -reward

    # ------------------------------------------------------------------
    # Self-play transition (single policy controls the active player)
    # ------------------------------------------------------------------
    def _step_self_play(self, parsed: str) -> float:
        player = self._active_player

        if self._phase == "action":
            if parsed == "pass":
                self._last_event = f"P{player} passed turn"
                self._pass_action(player)
                return 0.0
            if parsed.startswith("pitch "):
                return self._do_pitch(player, int(parsed.split(" ")[1]))
            if parsed.startswith("play "):
                return self._do_play_attack(player, int(parsed.split(" ")[1]))
            return 0.0

        if self._phase == "defense":
            if parsed == "pass":
                self._pass_defense(player)
                return 0.0
            if parsed.startswith("block "):
                return self._do_block(player, int(parsed.split(" ")[1]))
            return 0.0

        if self._phase == "reaction":
            if parsed == "pass":
                return self._resolve_and_advance(player)
            if parsed.startswith("reaction "):
                return self._do_reaction(player, int(parsed.split(" ")[1]))
            return 0.0

        return 0.0

    # ------------------------------------------------------------------
    # Opponent automation (non-self-play): drive player 1 until it is the
    # agent's turn to decide, or the game ends.
    # ------------------------------------------------------------------
    def _auto_advance(self) -> float:
        accum = 0.0
        guard = 0
        while not self._is_terminal() and guard < 2000:
            guard += 1
            phase = self._phase
            if self._active_player == 0:
                if phase == "action":
                    return accum
                if phase == "defense":
                    if self._legal_blocks(0):
                        return accum
                    self._pass_defense(0)
                    continue
                if phase == "reaction":
                    if self._legal_reactions(0):
                        return accum
                    accum += self._resolve_and_advance(0)
                    continue
                return accum

            # Opponent (player 1) to act.
            if phase == "action":
                accum += self._opponent_action()
            elif phase == "defense":
                self._opponent_block()
            elif phase == "reaction":
                accum += self._resolve_and_advance(0)
            else:
                return accum
        return accum

    def _opponent_prepare_resources(self, budget: int = 3) -> None:
        """Auto-pitch low-value cards so the scripted opponent can afford a play."""
        opp = self._players[1]
        guard = 0
        while opp.resources < budget and guard < 12:
            guard += 1
            best_idx: Optional[int] = None
            best_rank: Optional[tuple[int, int]] = None
            for i, cid in enumerate(opp.hand):
                card = self._cards[cid]
                if card.pitch <= 0:
                    continue
                # Prefer pitching non-attacks and weaker cards.
                is_attack = 1 if "attack_action" in card.card_types else 0
                rank = (is_attack, card.power + card.defense)
                if best_rank is None or rank < best_rank:
                    best_rank = rank
                    best_idx = i
            if best_idx is None:
                break
            self._do_pitch(1, best_idx)

    def _opponent_action(self) -> float:
        opp = self._players[1]
        self._opponent_prepare_resources()
        try:
            idx = self._opponent_policy.select_attack_index(self)
        except Exception:
            self._opponent_type = "preset_logic"
            self._opponent_policy = self._build_opponent_policy(self._opponent_type)
            idx = self._opponent_policy.select_attack_index(self)
        if idx is None or idx < 0 or idx >= len(opp.hand):
            self._last_event = "Opponent passed"
            self._pass_action(1)
            return 0.0
        return self._do_play_attack(1, idx)

    def _opponent_block(self) -> None:
        combat = self._pending_combat
        if combat is None or combat.defender != 1:
            self._pass_defense(1)
            return
        defender = self._players[1]
        guard = 0
        while combat is self._pending_combat and guard < 12:
            guard += 1
            remaining = combat.attack_power + combat.attack_bonus - sum(b[2] for b in combat.blocks)
            if remaining <= 0:
                break
            if combat.dominate and combat.blocks:
                break
            try:
                bidx = self._opponent_policy.select_block_index(self)
            except Exception:
                self._opponent_type = "preset_logic"
                self._opponent_policy = self._build_opponent_policy(self._opponent_type)
                bidx = self._opponent_policy.select_block_index(self)
            if bidx is None or bidx < 0 or bidx >= len(defender.hand):
                break
            self._do_block(1, bidx)
        self._pass_defense(1)

    def _legal_actions(self) -> list[str]:
        if self._selection_stage:
            return [f"choose_deck {o['key']}" for o in self._deck_options_for_format()]
        if not self._initialized or len(self._players) < 2:
            return ["pass"]
        if self._is_terminal():
            return []

        actor_idx = self._active_player
        if not self._self_play and actor_idx != 0:
            return ["pass"]

        if self._phase == "action":
            actions = ["pass"]
            actions.extend(f"pitch {i}" for i in self._legal_pitches(actor_idx))
            actions.extend(f"play {i}" for i in self._legal_plays(actor_idx))
            return actions

        if self._phase == "defense":
            if self._pending_combat is None or self._pending_combat.defender != actor_idx:
                return ["pass"]
            actions = ["pass"]
            actions.extend(f"block {i}" for i in self._legal_blocks(actor_idx))
            return actions

        if self._phase == "reaction":
            if self._pending_combat is None or self._pending_combat.attacker != actor_idx:
                return ["pass"]
            actions = ["pass"]
            actions.extend(f"reaction {i}" for i in self._legal_reactions(actor_idx))
            return actions

        return ["pass"]

    def _is_terminal(self) -> bool:
        if not self._players:
            return False
        return self._players[0].life <= 0 or self._players[1].life <= 0

    def _normalize_action(self, action: Any) -> str:
        if self._selection_stage and isinstance(action, str):
            return action.strip().lower()
        if isinstance(action, int):
            if self._phase == "action":
                return f"play {action}"
            if self._phase == "defense":
                return f"block {action}"
            if self._phase == "reaction":
                return f"reaction {action}"
        text = str(action).strip().lower()
        if text in {"pass", "end", "end turn"}:
            return "pass"
        for verb in ("play", "block", "pitch", "reaction"):
            if text.startswith(verb):
                parts = text.split()
                if len(parts) == 2 and parts[1].isdigit():
                    return f"{verb} {parts[1]}"
        return text

    def _observation(self) -> dict[str, Any]:
        if self._selection_stage:
            return {
                "turn": self._turn,
                "format": self._format,
                "stage": "deck_selection",
                "phase": self._phase,
                "active_player": self._active_player,
                "opponent_type": self._opponent_type,
                "deck_options": self._deck_options_for_format(),
                "selected_deck": self._selected_deck_option,
                "matchup": self._selected_opponent_deck_option,
                "legal_actions": self._legal_actions(),
                "last_event": self._last_event,
            }

        agent = self._players[0]
        opp = self._players[1]

        hand_view = []
        for i, cid in enumerate(agent.hand):
            c = self._cards[cid]
            hand_view.append(
                {
                    "index": i,
                    "id": c.id,
                    "name": c.name,
                    "pitch": c.pitch,
                    "cost": c.cost,
                    "power": c.power,
                    "defense": c.defense,
                    "card_types": list(c.card_types),
                    "keywords": list(c.keywords),
                    "text": c.text,
                }
            )

        pending = None
        if self._pending_combat is not None:
            pc = self._pending_combat
            attack_card = self._cards[pc.attack_card_id]
            pending = {
                "attacker": pc.attacker,
                "defender": pc.defender,
                "attack_card": attack_card.name,
                "attack_power": pc.attack_power + pc.attack_bonus,
                "attack_bonus": pc.attack_bonus,
                "total_block": sum(b[2] for b in pc.blocks),
                "go_again": pc.go_again,
                "dominate": pc.dominate,
            }

        return {
            "turn": self._turn,
            "format": self._format,
            "stage": "play",
            "phase": self._phase,
            "active_player": self._active_player,
            "opponent_type": self._opponent_type,
            "selected_deck": self._selected_deck_option,
            "matchup": self._selected_opponent_deck_option,
            "agent": {
                "hero": agent.hero.name,
                "life": agent.life,
                "resources": agent.resources,
                "action_points": agent.action_points,
                "deck": len(agent.deck),
                "discard": len(agent.discard),
                "hand": hand_view,
            },
            "opponent": {
                "hero": opp.hero.name,
                "life": opp.life,
                "resources": opp.resources,
                "action_points": opp.action_points,
                "deck": len(opp.deck),
                "discard": len(opp.discard),
                "hand_size": len(opp.hand),
            },
            "pending_combat": pending,
            "legal_actions": self._legal_actions(),
            "last_event": self._last_event,
        }

    def _estimate_win_probabilities(self, obs: Optional[dict[str, Any]] = None) -> tuple[float, float]:
        """Heuristic win probability estimate from current FaB state.

        Returns ``(agent_win_prob, opponent_win_prob)``.
        """
        if obs is None:
            obs = self._observation()

        if obs.get("stage") == "deck_selection":
            return 0.5, 0.5

        agent = obs.get("agent") if isinstance(obs.get("agent"), dict) else {}
        opp = obs.get("opponent") if isinstance(obs.get("opponent"), dict) else {}

        agent_life = float(agent.get("life", 0.0))
        opp_life = float(opp.get("life", 0.0))

        if opp_life <= 0 < agent_life:
            return 1.0, 0.0
        if agent_life <= 0 < opp_life:
            return 0.0, 1.0

        agent_hand_size = len(agent.get("hand", [])) if isinstance(agent.get("hand"), list) else 0
        opp_hand_size = int(opp.get("hand_size", 0) or 0)
        agent_resources = float(agent.get("resources", 0.0))
        opp_resources = float(opp.get("resources", 0.0))
        agent_ap = float(agent.get("action_points", 0.0))
        opp_ap = float(opp.get("action_points", 0.0))
        agent_deck = float(agent.get("deck", 0.0))
        opp_deck = float(opp.get("deck", 0.0))

        agent_score = (
            1.8 * agent_life
            + 1.0 * agent_hand_size
            + 0.6 * agent_resources
            + 0.8 * agent_ap
            + 0.05 * agent_deck
        )
        opp_score = (
            1.8 * opp_life
            + 1.0 * opp_hand_size
            + 0.6 * opp_resources
            + 0.8 * opp_ap
            + 0.05 * opp_deck
        )

        pending = obs.get("pending_combat")
        if isinstance(pending, dict):
            atk = float(pending.get("attack_power", 0.0) or 0.0)
            blk = float(pending.get("total_block", 0.0) or 0.0)
            net = max(0.0, atk - blk)
            attacker = int(pending.get("attacker", 0) or 0)
            if attacker == 0:
                agent_score += 1.5 * net
            else:
                opp_score += 1.5 * net

        active_player = int(obs.get("active_player", 0) or 0)
        if active_player == 0:
            agent_score += 0.4
        else:
            opp_score += 0.4

        diff = (agent_score - opp_score) / 8.0
        agent_p = 1.0 / (1.0 + math.exp(-diff))
        agent_p = max(0.0, min(1.0, agent_p))
        return agent_p, 1.0 - agent_p

    def _render_text(self) -> str:
        obs = self._observation()
        if obs.get("stage") == "deck_selection":
            lines = [
                "Flesh and Blood (Talishar-inspired)",
                f"Format: {obs['format']} | Stage: deck_selection",
                "Choose a deck:",
            ]
            for item in obs.get("deck_options", []):
                lines.append(f"  - {item['label']} ({item['deck_size']} cards) -> choose_deck {item['key']}")
            lines.append("Legal actions: " + ", ".join(obs.get("legal_actions", [])))
            return "\n".join(lines)

        p_agent, p_opp = self._estimate_win_probabilities(obs)
        lines = [
            "Flesh and Blood (Talishar-inspired)",
            f"Turn: {obs['turn']} | Format: {obs['format']} | Phase: {obs['phase']} | Active: P{obs['active_player']}",
            f"Agent ({obs['agent']['hero']}): life={obs['agent']['life']} hand={len(obs['agent']['hand'])} resources={obs['agent']['resources']} AP={obs['agent']['action_points']}",
            f"Opponent ({obs['opponent']['hero']}): life={obs['opponent']['life']} hand={obs['opponent']['hand_size']} resources={obs['opponent']['resources']} AP={obs['opponent']['action_points']}",
            f"Win % | Agent: {p_agent:.1%}  Opponent: {p_opp:.1%}",
            f"Last event: {obs['last_event']}",
            "Legal actions: " + ", ".join(obs["legal_actions"]),
        ]
        if obs["pending_combat"]:
            lines.append(
                "Combat: "
                f"{obs['pending_combat']['attack_card']} "
                f"atk={obs['pending_combat']['attack_power']} "
                f"block={obs['pending_combat']['total_block']}"
            )
        return "\n".join(lines)
